### PR TITLE
Revise CoC to be more explicit about unacceptable behavior

### PR DESCRIPTION
**Pull request by mgold**
This patch is split into three commits. The first two are pretty unexciting.

The third commit revises the actual content of the CoC. My main goals in doing so are:
- Be more explicit, defining words like "friendly", "helpful", and "considerate". Revise the definition of "microagression" to sound reasonable to someone who isn't an activist.
- Remove concern that a reasonable person could accidentally violate a rule
- In addition to stating rules and consequences, state the values of the community, and things to keep in mind when participating

I don't think anything will be particularly controversial but I'm open to splitting this into multiple commits and PRs if necessary.

### CODE REVIEW

**Comment by eeue56** [comment]
I'm not 100% convinced this addresses everything that people brought up. It reads too formal. I'd prefer an opening to have something like

>  The Elm Slack community is a welcoming environment where everyone can seek help, no matter how big or small their problems are. Members are encouraged to discuss any Elm-related topic. In order to make sure that our Slack remains as friendly as it currently is, we have some standard rules that we follow when discussing things. This document aims to highlight these.

which will help point out that our community is currently friendly and welcoming, and we want to keep it that way

**Comment by mgold** [comment]
I tried to err on the side of not making large changes, which explains in part why I left the opening mostly intact. A CoC needs to do multiple things, and one of them is to disavow discrimination, threats, and harassment. It needs to assure members of minority groups that strong, legal-like mechanisms are in place should such behavior occur.

As white guys, we don't get to complain about this. Yes, the opening is strong and formal. I can try to reduce that tone in the rest of the document. There is a place for statements of values as well.

**Comment by mgold** [comment]
I've adapted @eeue56's suggested paragraph as an intro. It actually reads a lot nicer than jumping straight into legalese. Good idea!

**Comment by eeue56** [comment]
I like how this reads a lot better :+1:

**Comment by mgold** [comment]
Great, thanks for your help.

**Comment by sporto** [comment]
Great, thanks for this

**Comment by mgold** [comment]
No problem, thanks for merging.

**Pull request merged**
